services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: aws-project-app:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=jpa
    restart: always
