server.port=8080
spring.application.name=aws-project
spring.profiles.active=jpa
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-exception=false
spring.mvc.problemdetails.enabled=true

# Configuración de Base de Datos PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/mydatabase}
spring.datasource.username=${DB_USERNAME:myuser}
spring.datasource.password=${DB_PASSWORD:secret}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.docker.compose.enabled=true
