server.port=8081
spring.application.name=aws-project
spring.profiles.active=memory
# Configuración de Base de Datos (ejemplo PostgreSQL)
#spring.datasource.url=jdbc:postgresql://localhost:5432/mi_db
#spring.datasource.username=usuario
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=update

