server.port=8080
spring.application.name=aws-project
spring.profiles.active=memory
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-exception=false
spring.mvc.problemdetails.enabled=true

# Configuración de Base de Datos (ejemplo PostgreSQL)
#spring.datasource.url=jdbc:postgresql://localhost:5432/mi_db
#spring.datasource.username=usuario
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=update

